### ISSUE TITLE
Error after Internet outage

### ISSUE THREAD

**Issue by yuukiw** [Arks-Layer/PSO2Tweaker#60]
A friend of mine started downloading tghe game with the Tweaker when his Internet Connection had an small outage. After restarting tweaker again it gave this message.
```
Program started...
Loading sidebar page...
Program opened successfully! Version 3.1.4.4 [OK!]
Checking for updates, please wait a moment...
ERROR -  - System.InvalidOperationException: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Control does not support transparent background colors. ---&gt; System.ArgumentException: Control does not support transparent background colors.
   at https://t.co/RZc9qduSQ6.Forms.Control.set_BackColor(Color value)
   at PSO2_Tweaker.frmDownloader.InitializeComponent()
   at PSO2_Tweaker.frmDownloader..ctor()
   --- End of inner exception stack trace ---
   at PSO2_Tweaker.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at PSO2_Tweaker.My.MyProject.MyForms.get_frmDownloader()
   at PSO2_Tweaker.FrmMain.VB$StateMachine_24_frmMain_Load.MoveNext()
[Error] Inner Exception: System.ArgumentException: Control does not support transparent background colors.
   at https://t.co/RZc9qduSQ6.Forms.Control.set_BackColor(Color value)
   at PSO2_Tweaker.frmDownloader.InitializeComponent()
   at PSO2_Tweaker.frmDownloader..ctor()
All done - System ready!
```

After a few restarts of the Tweaker the error disappeared but so did all already downloaded files,

**Comment by TheCrimsonDevil** [comment]
The "already downloaded files" did not disappear. The Tweaker does not do anything like that.

Also, the error described was already fixed - Have them redownload the latest version from Arks-Layer. It will *say* it's the same version, but it will fix the issue.
